"""
orchestrator.py — LangGraph Round Table orchestrator.

State contains ONLY orchestration metadata — never A2A communication content.
All actual agent communication travels exclusively via A2A peer messages.
"""
from __future__ import annotations

import ast
import asyncio
import json
import os
import sys
import uuid
sys.path.insert(0, os.path.dirname(__file__))
sys.path.insert(0, str(__import__('pathlib').Path(__file__).resolve().parent.parent.parent.parent))

import httpx
from langgraph.graph import StateGraph, END
from typing import TypedDict

from shared.base_agent import _auth_headers
from shared.discover import find_agent_by_name
from shared.models import (
    Artifact, DataPart, Message, Task,
    TaskSendParams, TaskState,
    get_artifact_text, text_artifact,
)
from logger_rt import (
    new_session, log_round_start, log_round_end, log_consensus, log_metric,
)
from tools.executor import run_python as _exec_python


# ── LangGraph state — orchestration metadata ONLY ─────────────────────────────

class RoundTableState(TypedDict):
    session_id: str           # unique session identifier
    task: str                 # original coding task
    round: int                # current round number
    max_rounds: int           # maximum rounds = 4
    test_suite: list[dict]    # generated by TestGeneratorAgent at start
    agent_outputs: dict       # latest output per agent (final collection)
    terminated: bool          # whether system has terminated
    termination_reason: str   # "max_rounds" or "consensus"


# ── HTTP helper ───────────────────────────────────────────────────────────────

async def _post_agent(
    http: httpx.AsyncClient,
    url: str,
    task_id: str,
    data: dict,
    session_id: str,
    timeout: float = 1800.0,
) -> dict:
    """POST to an agent's /tasks/send and return raw JSON dict."""
    params = TaskSendParams(
        id=task_id,
        sessionId=session_id,
        message=Message(role="user", parts=[DataPart(data=data)]),
    )
    resp = await http.post(
        f"{url}/tasks/send",
        json=params.model_dump(mode="json"),
        headers={**_auth_headers(), "X-Sender": "Orchestrator"},
        timeout=timeout,
    )
    resp.raise_for_status()
    return resp.json()


def _extract_artifact_text(raw: dict, name: str, fallback: str = "") -> str:
    """Extract text from a named artifact in a raw Task dict."""
    try:
        task = Task.model_validate(raw)
        return get_artifact_text(task, name)
    except Exception:
        return fallback


# ── Consensus / test runner ───────────────────────────────────────────────────

async def _run_test_suite(code: str, test_suite: list[dict]) -> tuple[int, int]:
    """
    Run the test suite against the given code.
    Returns (passed, total).
    Tries to find the first function in the code and call it with each test input.
    """
    if not code or not test_suite:
        return 0, 0

    # Find first function name via AST
    try:
        tree = ast.parse(code)
        func_names = [
            n.name for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)
        ]
        if not func_names:
            return 0, len(test_suite)
        func_name = func_names[0]
    except SyntaxError:
        return 0, len(test_suite)

    test_cases_json = json.dumps(test_suite)
    harness = f"""\
{code}

import json as _json
_test_cases = {test_cases_json}
_results = []
for _tc in _test_cases:
    try:
        _got = {func_name}(*_tc["input"])
        _results.append(_got == _tc["expected_output"])
    except Exception:
        _results.append(False)
print(_json.dumps(_results))
"""
    result = await asyncio.to_thread(_exec_python, harness, 30)
    if result["success"] and result["stdout"].strip():
        try:
            passes = json.loads(result["stdout"].strip())
            return sum(1 for p in passes if p), len(passes)
        except Exception:
            pass
    return 0, len(test_suite)


# ── Graph nodes ───────────────────────────────────────────────────────────────

async def initialize_node(state: RoundTableState) -> dict:
    """Generate session ID, call TestGeneratorAgent, set initial state."""
    task = state["task"]
    session_id = new_session(task)

    test_gen_card = await find_agent_by_name("Test Generator Agent")

    async with httpx.AsyncClient() as http:
        raw = await _post_agent(
            http, test_gen_card.url,
            f"{session_id}-testgen",
            {"task": task},
            session_id,
            timeout=600.0,
        )

    test_suite_json = _extract_artifact_text(raw, "test_suite", "[]")
    try:
        test_suite = json.loads(test_suite_json)
        if not isinstance(test_suite, list):
            test_suite = []
    except json.JSONDecodeError:
        test_suite = []

    log_metric(session_id, 0, "session_start", {"task": task, "test_count": len(test_suite)})

    return {
        "session_id": session_id,
        "round": 1,
        "test_suite": test_suite,
        "agent_outputs": {},
        "terminated": False,
        "termination_reason": "",
    }


async def run_round_node(state: RoundTableState) -> dict:
    """
    Advance one round by invoking only the Architect entrypoint.
    Orchestrator does not coordinate peer-to-peer messaging.
    """
    round_num = state["round"]
    session_id = state["session_id"]
    task = state["task"]
    max_rounds = state["max_rounds"]

    log_round_start(session_id, round_num, max_rounds, task)

    # Orchestrator only talks to Architect Agent.
    # Architect discovers and coordinates the other agents via registry.
    arch_card = await find_agent_by_name("Architect Agent")

    payload = {
        "task": task,
        "round": round_num,
        "max_rounds": max_rounds,
        "session_id": session_id,
    }

    agent_outputs: dict[str, str] = {
        "Architect": "",
        "Coder": "",
        "Debugger": "",
        "Tester": "",
    }
    try:
        async with httpx.AsyncClient() as http:
            architect_result = await _post_agent(
                http,
                arch_card.url,
                f"{session_id}-r{round_num}-architect",
                payload,
                session_id,
                timeout=300.0,
            )
        agent_outputs["Architect"] = _extract_artifact_text(
            architect_result, "architect_approach", ""
        )
        round_bundle_raw = _extract_artifact_text(
            architect_result, "round_bundle", "{}"
        )
        try:
            round_bundle = json.loads(round_bundle_raw)
            if isinstance(round_bundle, dict):
                agent_outputs["Coder"] = str(round_bundle.get("Coder", ""))
                agent_outputs["Debugger"] = str(round_bundle.get("Debugger", ""))
                agent_outputs["Tester"] = str(round_bundle.get("Tester", ""))
        except Exception:
            pass
    except Exception as exc:
        print(f"[Orchestrator] Architect failed: {exc}", flush=True)

    log_round_end(session_id, round_num, agent_outputs)

    return {
        "round": round_num + 1,
        "agent_outputs": agent_outputs,
    }


async def check_termination_node(state: RoundTableState) -> dict:
    """
    Decide whether to terminate.
    - If round > max_rounds → "max_rounds"
    - If all agents produced output AND code passes all tests → "consensus"
    """
    round_num = state["round"]        # already incremented by run_round
    max_rounds = state["max_rounds"]
    session_id = state["session_id"]

    if round_num > max_rounds:
        log_consensus(session_id, round_num - 1, "max_rounds")
        return {"terminated": True, "termination_reason": "max_rounds"}

    # Consensus check
    agent_outputs = state.get("agent_outputs", {})
    all_produced = all(agent_outputs.get(name, "") for name in
                       ("Architect", "Coder", "Debugger", "Tester"))

    if all_produced:
        coder_code = agent_outputs.get("Coder", "")
        test_suite = state.get("test_suite", [])
        passed, total = await _run_test_suite(coder_code, test_suite)

        if total > 0 and passed == total:
            log_consensus(session_id, round_num - 1, "consensus")
            log_metric(session_id, round_num - 1, "test_result", {
                "pass_rate": 1.0, "passed": passed, "total": total,
            })
            return {"terminated": True, "termination_reason": "consensus"}

        if total > 0:
            log_metric(session_id, round_num - 1, "test_result", {
                "pass_rate": round(passed / total, 2),
                "passed": passed,
                "total": total,
            })

    return {"terminated": False, "termination_reason": ""}


async def collect_results_node(state: RoundTableState) -> dict:
    """Call CodeValidatorAgent on final code, log session end, return results."""
    session_id = state["session_id"]
    task = state["task"]
    agent_outputs = state.get("agent_outputs", {})
    coder_code = agent_outputs.get("Coder", "")
    total_rounds = state["round"] - 1
    termination_reason = state["termination_reason"]

    validation_report = "{}"
    try:
        validator_card = await find_agent_by_name("Code Validator Agent")
        async with httpx.AsyncClient() as http:
            raw = await _post_agent(
                http, validator_card.url,
                f"{session_id}-validate",
                {"code": coder_code, "task": task},
                session_id,
                timeout=120.0,
            )
        validation_report = _extract_artifact_text(raw, "validation_report", "{}")
    except Exception as exc:
        print(f"[Orchestrator] CodeValidator failed: {exc}", flush=True)

    # Run final test suite pass rate
    test_suite = state.get("test_suite", [])
    passed, total = await _run_test_suite(coder_code, test_suite)
    final_pass_rate = round(passed / total, 2) if total > 0 else 0.0

    log_metric(session_id, total_rounds, "session_end", {
        "total_rounds": total_rounds,
        "final_pass_rate": final_pass_rate,
        "termination_reason": termination_reason,
    })

    return {
        "agent_outputs": {
            **agent_outputs,
            "validation_report": validation_report,
            "final_pass_rate": str(final_pass_rate),
        }
    }


# ── Routing function ──────────────────────────────────────────────────────────

def _route(state: RoundTableState) -> str:
    return "collect_results" if state["terminated"] else "run_round"


# ── Graph builder ─────────────────────────────────────────────────────────────

def build_graph():
    workflow = StateGraph(RoundTableState)

    workflow.add_node("initialize",        initialize_node)
    workflow.add_node("run_round",         run_round_node)
    workflow.add_node("check_termination", check_termination_node)
    workflow.add_node("collect_results",   collect_results_node)

    workflow.set_entry_point("initialize")
    workflow.add_edge("initialize",        "run_round")
    workflow.add_edge("run_round",         "check_termination")
    workflow.add_conditional_edges(
        "check_termination",
        _route,
        {"run_round": "run_round", "collect_results": "collect_results"},
    )
    workflow.add_edge("collect_results", END)

    return workflow.compile()


# ── Entry point for standalone use ───────────────────────────────────────────

async def run(task: str, max_rounds: int = 4) -> RoundTableState:
    graph = build_graph()
    initial_state: RoundTableState = {
        "session_id": "",
        "task": task,
        "round": 1,
        "max_rounds": max_rounds,
        "test_suite": [],
        "agent_outputs": {},
        "terminated": False,
        "termination_reason": "",
    }
    return await graph.ainvoke(initial_state)
